import 'bootstrap/dist/css/bootstrap.css';
import { Poppins } from 'next/font/google';
import BootstrapClient from '@/components/BootstrapClient.js';

import "./globals.css";

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins',
})

export const metadata = {
  title: "MemaTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
