import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from '@/components/BootstrapClient.js';

import Head from 'next/head';
import favicon from '@/public/images/logo.png';

import { Poppins } from 'next/font/google';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core"; 
config.autoAddCss = false;

import "./globals.css";

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins',
});

export const metadata = {
  title: "MemaTech",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "@/public/images/logo.png"
    }
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
      {/* <Head>
          <link rel="icon" href={favicon} type="image/png" sizes="any" />
      </Head> */}
        {/* <link rel="icon" href={favicon} sizes="any" /> */}
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
